# Generated by Django 6.0.5 on 2026-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('company', 'Company Project'), ('personal', 'Personal Project'), ('wordpress', 'WordPress Website')], default='personal', help_text='Category for filtering: Company, Personal, or WordPress.', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Optional CSS icon class (e.g. devicon-python-plain). Auto-detected if blank.', max_length=100),
        ),
    ]
